/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_page_acc (void)
{
  GtkWidget *page_acc;
  GtkWidget *fixed1;
  GtkWidget *label2;
  GtkWidget *button2;
  GtkWidget *button1;
  GtkWidget *notebook1;
  GtkWidget *fixed5;
  GtkWidget *treeview1;
  GtkWidget *label3;
  GtkWidget *fixed4;
  GtkWidget *treeview2;
  GtkWidget *label4;
  GtkWidget *fixed3;
  GtkWidget *treeview3;
  GtkWidget *label5;
  GtkWidget *fixed2;
  GtkWidget *treeview4;
  GtkWidget *label6;
  GtkWidget *label1;

  page_acc = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (page_acc), _("window1"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (page_acc), fixed1);

  label2 = gtk_label_new (_("ou"));
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed1), label2, 512, 16);
  gtk_widget_set_size_request (label2, 41, 17);

  button2 = gtk_button_new_with_mnemonic (_("Se connecter"));
  gtk_widget_show (button2);
  gtk_fixed_put (GTK_FIXED (fixed1), button2, 544, 8);
  gtk_widget_set_size_request (button2, 108, 29);

  button1 = gtk_button_new_with_mnemonic (_("S'inscrire"));
  gtk_widget_show (button1);
  gtk_fixed_put (GTK_FIXED (fixed1), button1, 432, 8);
  gtk_widget_set_size_request (button1, 88, 29);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_fixed_put (GTK_FIXED (fixed1), notebook1, 64, 96);
  gtk_widget_set_size_request (notebook1, 536, 352);

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed5);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed5), treeview1, 104, 72);
  gtk_widget_set_size_request (treeview1, 300, 200);

  label3 = gtk_label_new (_("H\303\264tels"));
  gtk_widget_show (label3);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label3);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed4);

  treeview2 = gtk_tree_view_new ();
  gtk_widget_show (treeview2);
  gtk_fixed_put (GTK_FIXED (fixed4), treeview2, 104, 72);
  gtk_widget_set_size_request (treeview2, 300, 200);

  label4 = gtk_label_new (_("Vols"));
  gtk_widget_show (label4);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label4);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed3);

  treeview3 = gtk_tree_view_new ();
  gtk_widget_show (treeview3);
  gtk_fixed_put (GTK_FIXED (fixed3), treeview3, 96, 72);
  gtk_widget_set_size_request (treeview3, 300, 200);

  label5 = gtk_label_new (_("Voitures"));
  gtk_widget_show (label5);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), label5);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed2);

  treeview4 = gtk_tree_view_new ();
  gtk_widget_show (treeview4);
  gtk_fixed_put (GTK_FIXED (fixed2), treeview4, 112, 72);
  gtk_widget_set_size_request (treeview4, 300, 200);

  label6 = gtk_label_new (_("S\303\251jours"));
  gtk_widget_show (label6);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 3), label6);

  label1 = gtk_label_new (_("<b><i><span foreground =\"#405AEA\" size =\"xx-large\">Sky Travel </span></i></b>"));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed1), label1, 0, 0);
  gtk_widget_set_size_request (label1, 144, 40);
  gtk_label_set_use_markup (GTK_LABEL (label1), TRUE);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (page_acc, page_acc, "page_acc");
  GLADE_HOOKUP_OBJECT (page_acc, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (page_acc, label2, "label2");
  GLADE_HOOKUP_OBJECT (page_acc, button2, "button2");
  GLADE_HOOKUP_OBJECT (page_acc, button1, "button1");
  GLADE_HOOKUP_OBJECT (page_acc, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (page_acc, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (page_acc, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (page_acc, label3, "label3");
  GLADE_HOOKUP_OBJECT (page_acc, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (page_acc, treeview2, "treeview2");
  GLADE_HOOKUP_OBJECT (page_acc, label4, "label4");
  GLADE_HOOKUP_OBJECT (page_acc, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (page_acc, treeview3, "treeview3");
  GLADE_HOOKUP_OBJECT (page_acc, label5, "label5");
  GLADE_HOOKUP_OBJECT (page_acc, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (page_acc, treeview4, "treeview4");
  GLADE_HOOKUP_OBJECT (page_acc, label6, "label6");
  GLADE_HOOKUP_OBJECT (page_acc, label1, "label1");

  return page_acc;
}

GtkWidget*
create_inscrire (void)
{
  GtkWidget *inscrire;
  GtkWidget *fixed6;
  GtkWidget *entry1;
  GtkWidget *entry2;
  GtkWidget *entry3;
  GtkWidget *entry4;
  GtkWidget *entry5;
  GtkObject *spinbutton1_adj;
  GtkWidget *spinbutton1;
  GtkWidget *entry6;
  GtkWidget *entry7;
  GtkWidget *radiobutton2;
  GSList *radiobutton2_group = NULL;
  GtkWidget *radiobutton1;
  GtkWidget *label16;
  GtkWidget *label20;
  GtkWidget *label21;
  GtkWidget *label19;
  GtkWidget *comboboxentry1;
  GtkWidget *label18;
  GtkWidget *label17;
  GtkWidget *label12;
  GtkWidget *label13;
  GtkWidget *label14;
  GtkWidget *label15;
  GtkWidget *label11;
  GtkWidget *button4;
  GtkWidget *button3;
  GtkWidget *label22;
  GtkWidget *label10;

  inscrire = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (inscrire), _("window2"));

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (inscrire), fixed6);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_fixed_put (GTK_FIXED (fixed6), entry1, 168, 112);
  gtk_widget_set_size_request (entry1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 8226);

  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_fixed_put (GTK_FIXED (fixed6), entry2, 168, 152);
  gtk_widget_set_size_request (entry2, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2), 8226);

  entry3 = gtk_entry_new ();
  gtk_widget_show (entry3);
  gtk_fixed_put (GTK_FIXED (fixed6), entry3, 168, 192);
  gtk_widget_set_size_request (entry3, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3), 8226);

  entry4 = gtk_entry_new ();
  gtk_widget_show (entry4);
  gtk_fixed_put (GTK_FIXED (fixed6), entry4, 176, 256);
  gtk_widget_set_size_request (entry4, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry4), 8226);

  entry5 = gtk_entry_new ();
  gtk_widget_show (entry5);
  gtk_fixed_put (GTK_FIXED (fixed6), entry5, 176, 296);
  gtk_widget_set_size_request (entry5, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry5), 8226);

  spinbutton1_adj = gtk_adjustment_new (0, 0, 100, 1, 10, 10);
  spinbutton1 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1_adj), 1, 0);
  gtk_widget_show (spinbutton1);
  gtk_fixed_put (GTK_FIXED (fixed6), spinbutton1, 176, 376);
  gtk_widget_set_size_request (spinbutton1, 160, 27);

  entry6 = gtk_entry_new ();
  gtk_widget_show (entry6);
  gtk_fixed_put (GTK_FIXED (fixed6), entry6, 176, 408);
  gtk_widget_set_size_request (entry6, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry6), 8226);

  entry7 = gtk_entry_new ();
  gtk_widget_show (entry7);
  gtk_fixed_put (GTK_FIXED (fixed6), entry7, 176, 448);
  gtk_widget_set_size_request (entry7, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry7), 8226);

  radiobutton2 = gtk_radio_button_new_with_mnemonic (NULL, _("Femme"));
  gtk_widget_show (radiobutton2);
  gtk_fixed_put (GTK_FIXED (fixed6), radiobutton2, 264, 224);
  gtk_widget_set_size_request (radiobutton2, 118, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton2), radiobutton2_group);
  radiobutton2_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton2));

  radiobutton1 = gtk_radio_button_new_with_mnemonic (NULL, _("Homme"));
  gtk_widget_show (radiobutton1);
  gtk_fixed_put (GTK_FIXED (fixed6), radiobutton1, 176, 224);
  gtk_widget_set_size_request (radiobutton1, 118, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton1), radiobutton2_group);
  radiobutton2_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton1));

  label16 = gtk_label_new (_("Date de naissance:"));
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed6), label16, 32, 264);
  gtk_widget_set_size_request (label16, 145, 16);

  label20 = gtk_label_new (_("E-mail:"));
  gtk_widget_show (label20);
  gtk_fixed_put (GTK_FIXED (fixed6), label20, 120, 416);
  gtk_widget_set_size_request (label20, 49, 17);

  label21 = gtk_label_new (_("Tel:"));
  gtk_widget_show (label21);
  gtk_fixed_put (GTK_FIXED (fixed6), label21, 128, 456);
  gtk_widget_set_size_request (label21, 49, 17);

  label19 = gtk_label_new (_("Nombre d'enfants :"));
  gtk_widget_show (label19);
  gtk_fixed_put (GTK_FIXED (fixed6), label19, 32, 384);
  gtk_widget_set_size_request (label19, 145, 16);

  comboboxentry1 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry1);
  gtk_fixed_put (GTK_FIXED (fixed6), comboboxentry1, 176, 336);
  gtk_widget_set_size_request (comboboxentry1, 160, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("C\303\251libataire"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry1), _("Mari\303\251"));

  label18 = gtk_label_new (_("Etat civil:"));
  gtk_widget_show (label18);
  gtk_fixed_put (GTK_FIXED (fixed6), label18, 96, 344);
  gtk_widget_set_size_request (label18, 81, 17);

  label17 = gtk_label_new (_("Adresse:"));
  gtk_widget_show (label17);
  gtk_fixed_put (GTK_FIXED (fixed6), label17, 96, 304);
  gtk_widget_set_size_request (label17, 89, 16);

  label12 = gtk_label_new (_("Nom:"));
  gtk_widget_show (label12);
  gtk_fixed_put (GTK_FIXED (fixed6), label12, 120, 120);
  gtk_widget_set_size_request (label12, 49, 17);

  label13 = gtk_label_new (_("Prenom:"));
  gtk_widget_show (label13);
  gtk_fixed_put (GTK_FIXED (fixed6), label13, 96, 160);
  gtk_widget_set_size_request (label13, 81, 17);

  label14 = gtk_label_new (_("CIN:"));
  gtk_widget_show (label14);
  gtk_fixed_put (GTK_FIXED (fixed6), label14, 128, 200);
  gtk_widget_set_size_request (label14, 49, 17);

  label15 = gtk_label_new (_("Sexe:"));
  gtk_widget_show (label15);
  gtk_fixed_put (GTK_FIXED (fixed6), label15, 120, 232);
  gtk_widget_set_size_request (label15, 65, 16);

  label11 = gtk_label_new (_("<b><i><span foreground =\"#681126\">Veuillez remplir le formulaire ci-joint</span></i></b>"));
  gtk_widget_show (label11);
  gtk_fixed_put (GTK_FIXED (fixed6), label11, 64, 56);
  gtk_widget_set_size_request (label11, 304, 32);
  gtk_label_set_use_markup (GTK_LABEL (label11), TRUE);

  button4 = gtk_button_new_with_mnemonic (_("Retour"));
  gtk_widget_show (button4);
  gtk_fixed_put (GTK_FIXED (fixed6), button4, 16, 568);
  gtk_widget_set_size_request (button4, 68, 29);

  button3 = gtk_button_new_with_mnemonic (_("S'inscrire"));
  gtk_widget_show (button3);
  gtk_fixed_put (GTK_FIXED (fixed6), button3, 200, 520);
  gtk_widget_set_size_request (button3, 96, 29);

  label22 = gtk_label_new (_("<span foreground =\"#FF0000\"> * </span>: Champs obligatoires"));
  gtk_widget_show (label22);
  gtk_fixed_put (GTK_FIXED (fixed6), label22, 16, 504);
  gtk_widget_set_size_request (label22, 176, 17);
  gtk_label_set_use_markup (GTK_LABEL (label22), TRUE);

  label10 = gtk_label_new (_("<b><i><span foreground =\"#405AEA\" size =\"xx-large\">S'inscrire </span></i></b>"));
  gtk_widget_show (label10);
  gtk_fixed_put (GTK_FIXED (fixed6), label10, 0, 0);
  gtk_widget_set_size_request (label10, 128, 31);
  gtk_label_set_use_markup (GTK_LABEL (label10), TRUE);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (inscrire, inscrire, "inscrire");
  GLADE_HOOKUP_OBJECT (inscrire, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (inscrire, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (inscrire, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (inscrire, entry3, "entry3");
  GLADE_HOOKUP_OBJECT (inscrire, entry4, "entry4");
  GLADE_HOOKUP_OBJECT (inscrire, entry5, "entry5");
  GLADE_HOOKUP_OBJECT (inscrire, spinbutton1, "spinbutton1");
  GLADE_HOOKUP_OBJECT (inscrire, entry6, "entry6");
  GLADE_HOOKUP_OBJECT (inscrire, entry7, "entry7");
  GLADE_HOOKUP_OBJECT (inscrire, radiobutton2, "radiobutton2");
  GLADE_HOOKUP_OBJECT (inscrire, radiobutton1, "radiobutton1");
  GLADE_HOOKUP_OBJECT (inscrire, label16, "label16");
  GLADE_HOOKUP_OBJECT (inscrire, label20, "label20");
  GLADE_HOOKUP_OBJECT (inscrire, label21, "label21");
  GLADE_HOOKUP_OBJECT (inscrire, label19, "label19");
  GLADE_HOOKUP_OBJECT (inscrire, comboboxentry1, "comboboxentry1");
  GLADE_HOOKUP_OBJECT (inscrire, label18, "label18");
  GLADE_HOOKUP_OBJECT (inscrire, label17, "label17");
  GLADE_HOOKUP_OBJECT (inscrire, label12, "label12");
  GLADE_HOOKUP_OBJECT (inscrire, label13, "label13");
  GLADE_HOOKUP_OBJECT (inscrire, label14, "label14");
  GLADE_HOOKUP_OBJECT (inscrire, label15, "label15");
  GLADE_HOOKUP_OBJECT (inscrire, label11, "label11");
  GLADE_HOOKUP_OBJECT (inscrire, button4, "button4");
  GLADE_HOOKUP_OBJECT (inscrire, button3, "button3");
  GLADE_HOOKUP_OBJECT (inscrire, label22, "label22");
  GLADE_HOOKUP_OBJECT (inscrire, label10, "label10");

  return inscrire;
}

GtkWidget*
create_login (void)
{
  GtkWidget *login;
  GtkWidget *fixed7;
  GtkWidget *label23;
  GtkWidget *entry8;
  GtkWidget *entry9;
  GtkWidget *button5;
  GtkWidget *label25;
  GtkWidget *label24;
  GtkWidget *button6;

  login = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (login), _("window3"));

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (login), fixed7);

  label23 = gtk_label_new (_("<b><i><span foreground =\"#405AEA\" size =\"xx-large\">Se connecter</span></i></b>"));
  gtk_widget_show (label23);
  gtk_fixed_put (GTK_FIXED (fixed7), label23, 0, 0);
  gtk_widget_set_size_request (label23, 160, 48);
  gtk_label_set_use_markup (GTK_LABEL (label23), TRUE);

  entry8 = gtk_entry_new ();
  gtk_widget_show (entry8);
  gtk_fixed_put (GTK_FIXED (fixed7), entry8, 152, 128);
  gtk_widget_set_size_request (entry8, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry8), 8226);

  entry9 = gtk_entry_new ();
  gtk_widget_show (entry9);
  gtk_fixed_put (GTK_FIXED (fixed7), entry9, 152, 176);
  gtk_widget_set_size_request (entry9, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry9), 8226);

  button5 = gtk_button_new_with_mnemonic (_("Se connecter "));
  gtk_widget_show (button5);
  gtk_fixed_put (GTK_FIXED (fixed7), button5, 176, 224);
  gtk_widget_set_size_request (button5, 100, 29);

  label25 = gtk_label_new (_("Mot de passe:"));
  gtk_widget_show (label25);
  gtk_fixed_put (GTK_FIXED (fixed7), label25, 40, 184);
  gtk_widget_set_size_request (label25, 113, 16);

  label24 = gtk_label_new (_("Nom d'utilisateur:"));
  gtk_widget_show (label24);
  gtk_fixed_put (GTK_FIXED (fixed7), label24, 16, 136);
  gtk_widget_set_size_request (label24, 129, 17);

  button6 = gtk_button_new_with_mnemonic (_("Retour"));
  gtk_widget_show (button6);
  gtk_fixed_put (GTK_FIXED (fixed7), button6, 16, 272);
  gtk_widget_set_size_request (button6, 68, 29);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (login, login, "login");
  GLADE_HOOKUP_OBJECT (login, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (login, label23, "label23");
  GLADE_HOOKUP_OBJECT (login, entry8, "entry8");
  GLADE_HOOKUP_OBJECT (login, entry9, "entry9");
  GLADE_HOOKUP_OBJECT (login, button5, "button5");
  GLADE_HOOKUP_OBJECT (login, label25, "label25");
  GLADE_HOOKUP_OBJECT (login, label24, "label24");
  GLADE_HOOKUP_OBJECT (login, button6, "button6");

  return login;
}

